### ISSUE TITLE
The OCI profile into settings always DEFAULT

### ISSUE THREAD

**Issue by Madzi** [oracle/oci-toolkit-eclipse#7]
When I open eclipse global settings and try change profile from DEFAULT to any other there are no changes actually happens. It's looks like applied but after reopening settings I see again DEFAULT profile as main profile.

**Comment by anubrato** [comment]
Hi - Is there any tentative date for when this may be resolved? I faced the same issue as @Madzi has reported, and I am using the latest version 1.3.0.
Even after selecting the non-DEFAULT profile in the Preferences, the OCI Explorer view always picks up the DEFAULT.

**Comment by jyotisaini** [comment]
@Madzi  @anubrato : Thanks for reporting this. We have opened a task for this and will work on it soon.

**Comment by jyotisaini** [comment]
Hi, We are able to reproduce this issue and are currently working on the fix. As a work around, you can change profile by clicking the OCI plugin icon from the toolbar.

**Comment by jyotisaini** [comment]
Hi @Madzi  @anubrato  This issue has been fixed with the latest release(v1.3.1). Can you please give it a try before we close the issue? Thanks.

**Comment by anubrato** [comment]
Hi @jyotisaini Thanks for looking into this. I do see that now the Profile selection is persisted, but on clicking Apply I am getting the below stack trace
```
java.lang.LinkageError: ClassCastException: attempting to castbundleresource://1050.fwk1687442582/javax/ws/rs/client/ClientBuilder.class to bundleresource://1702.fwk1687442582:27/javax/ws/rs/client/ClientBuilder.class
	at javax.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:105)
	at com.oracle.bmc.http.internal.RestClientFactory.createClient(RestClientFactory.java:176)
	at com.oracle.bmc.http.internal.RestClientFactory.create(RestClientFactory.java:146)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:292)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:217)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:180)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:145)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:117)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:92)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:69)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:55)
	at com.oracle.bmc.objectstorage.ObjectStorageClient.<init>(ObjectStorageClient.java:44)
	at com.oracle.oci.eclipse.sdkclients.ObjStorageClient.createObjectStorageClient(ObjStorageClient.java:92)
	at com.oracle.oci.eclipse.sdkclients.ObjStorageClient.<init>(ObjStorageClient.java:55)
	at com.oracle.oci.eclipse.sdkclients.ObjStorageClient.getInstance(ObjStorageClient.java:61)
	at com.oracle.oci.eclipse.ui.account.ConfigurationWizard.doFinish(ConfigurationWizard.java:128)
	at com.oracle.oci.eclipse.ui.account.ConfigurationWizard.access$0(ConfigurationWizard.java:108)
	at com.oracle.oci.eclipse.ui.account.ConfigurationWizard$1.run(ConfigurationWizard.java:77)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

**Comment by jyotisaini** [comment]
Hi @anubrato I tried to reproduce this, but the plugins works perfectly fine when i install it.  Where does this stack trace show up ? In the Error wizard ? Also from the stack trace it looks like its calling `ConfigurationWizard.run()` method. This method is only called from configuration wizard not from the preference page. Can you try uninstalling and installing the plugin again ?

**Comment by jyotisaini** [comment]
Hi @anubrato : any update ?

**Comment by Madzi** [comment]
In version 1.3.1 I can switch between my profiles. The issue is done.

**Comment by anubrato** [comment]
Hi @jyotisaini - Apologies for the late reply. Yes, this issue is resolved
